name: Page Builder Test

# Controls when the workflow will run
on: [push]

jobs:
  page_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone manicjs/manic repository
        uses: actions/checkout@v2
        with:
          owner: 'manicjs'
          repository: 'manic'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd manic
          ls -la
